### ISSUE TITLE
Unable to import MP3 audio files

### ISSUE THREAD

**Issue by dklann** [ElvishArtisan/rivendell-install#1]
After a clean install of CentOS 7 Minimal, and a clean run of the C7 rivendell-install.sh script, then performing a database upgrade from version 220 to the current 259 (Rivendell version 2.15.2) I was unable to import properly formatted MP3 files into the Rivendell Library. Error from CLI rdimport is "**Audio Converter Error: Unsupported Format, skipping** [filename.mp3]..."

Running strace on the httpd process revealed that _rdxport.cgi_ could not find _libmad.so_ in any of the usual (per _/etc/ld.so.cache_) locations. The libmad package shows only _/usr/lib64/libmad.so.0_ and _/usr/lib64/libmad.so.0.2.1_. I manually created a symlink from the latter to _/usr/lib64/libmad.so_ and the MP3 import completed successfully.

Not sure if this is an issue with the libmad package (libmad-0.15.1b-19.el7.src.rpm) or with the compilation of _/var/www/rd-bin/rdxport.cgi_.

Is this the right place for this issue report?

Thanks!

**Comment by ElvishArtisan** [comment]
On Mar 16, 2017, at 10:24, David Klann <notifications@github.com> wrote:
> After a clean install of CentOS 7 Minimal, and a clean run of the C7 rivendell-install.sh script, then performing a database upgrade from version 220 to the current 259 (Rivendell version 2.15.2) I was unable to import properly formatted MP3 files into the Rivendell Library. Error from CLI rdimport is "Audio Converter Error: Unsupported Format, skipping [filename.mp3]..."
> 
> Running strace on the httpd process revealed that rdxport.cgi could not find libmad.so in any of the usual (per /etc/ld.so.cache) locations. The libmad package shows only /usr/lib64/libmad.so.0 and /usr/lib64/libmad.so.0.2.1. I manually created a symlink from the latter to /usr/lib64/libmad.so and the MP3 import completed successfully.
> 
> Not sure if this is an issue with the libmad package (libmad-0.15.1b-19.el7.src.rpm) or with the compilation of /var/www/rd-bin/rdxport.cgi.
> 

Known problem with Rivendell v2.15.2, which (incorrectly) links against libmp3lame.so instead of libmp3lame.so.0.  Already fixed in Git ‘stable’, will be released as part of v2.15.3.

> Is this the right place for this issue report?
> 

Yes.  Thank you.

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by dklann** [comment]
Since this is fixed in ElvishArtisan/rivendell, I'll close this issue.
